import {useEffect,useMemo,useState} from "react";

type Node={id:string;label:string;kind:string;x:number;y:number;capacity:number;occupancy:number};
type Edge={id:string;source:string;target:string;capacity_per_min:number;density:number;status:string};
type Snapshot={venue:{name:string;latitude:number;longitude:number};state:{status:string;sim_time_min:number;people_inside:number;total_entered:number;total_exited:number;risk_score:number;risk_level:string;bottlenecks:string[];events:any[];active_agents:number;reroutes:number};nodes:Node[];edges:Edge[]};

const API=import.meta.env.VITE_API_BASE_URL||"http://localhost:8000";
function App(){
 const [snap,setSnap]=useState<Snapshot|null>(null); const [scenario,setScenario]=useState("30,000 people arriving for an evening concert"); const [connected,setConnected]=useState(false);
 const load=async()=>{const r=await fetch(API+"/api/simulation"); setSnap(await r.json())};
 useEffect(()=>{load(); const ws=new WebSocket((import.meta.env.VITE_WS_BASE_URL||API.replace("http","ws"))+"/ws/simulation"); ws.onopen=()=>setConnected(true); ws.onclose=()=>setConnected(false); ws.onmessage=e=>setSnap(JSON.parse(e.data)); return()=>ws.close()},[]);
 const act=async(path:string,body?:any)=>{await fetch(API+path,{method:"POST",headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined}); load()};
 const nodes=useMemo(()=>snap?.nodes||[],[snap]); const edges=snap?.edges||[];
 return <div className="app"><header><div><b>CROWD FLOW</b><span> INTELLIGENCE</span><small>Venue operations & geospatial decision support</small></div><div className="status">● {connected?"LIVE":"OFFLINE"}</div></header>
 <main><aside><section><label>AI SCENARIO ASSISTANT</label><textarea value={scenario} onChange={e=>setScenario(e.target.value)}/><button onClick={async()=>{const r=await fetch(API+"/api/scenarios/parse",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:scenario})});const s=await r.json();await act("/api/simulation/scenario",s)}}>INTERPRET & SIMULATE</button></section>
 <section><label>RUN CONTROLS</label><div className="row"><button onClick={()=>act("/api/simulation/start")}>START</button><button onClick={()=>act("/api/simulation/pause")}>PAUSE</button><button onClick={()=>act("/api/simulation/reset")}>RESET</button></div></section>
 <section><label>EMERGENCY TEST</label><div className="row"><button onClick={()=>act("/api/simulation/emergency",{kind:"gate-failure",node_id:"gate-e"})}>GATE E</button><button onClick={()=>act("/api/simulation/emergency",{kind:"fire",node_id:"j-c"})}>FIRE</button></div><button onClick={()=>act("/api/simulation/emergency/clear")}>CLEAR INCIDENT</button></section>
 <section><label>GEO CONTEXT</label><p>Venue: {snap?.venue.name||"—"}</p><p>Lat/Lon: {snap?.venue.latitude.toFixed(4)}, {snap?.venue.longitude.toFixed(4)}</p><p className="muted">Public geospatial context is provider-backed; no unrestricted satellite/CCTV access is assumed.</p></section></aside>
 <div className="center"><div className="metrics">{[["PEOPLE",snap?.state.people_inside||0],["AGENTS",snap?.state.active_agents||0],["REROUTES",snap?.state.reroutes||0],["RISK",Math.round(snap?.state.risk_score||0)]].map(([k,v])=><div className="metric" key={k}><small>{k}</small><strong>{v}</strong></div>)}</div><div className="map"><div className="grid"></div>{edges.map(e=>{const a=nodes.find(n=>n.id===e.source),b=nodes.find(n=>n.id===e.target); if(!a||!b)return null; return <div key={e.id} className={"edge "+(e.density>.7?"hot":"")} style={{left:a.x+"%",top:a.y+"%",width:Math.hypot(b.x-a.x,b.y-a.y)+"%",transform:`rotate(${Math.atan2(b.y-a.y,b.x-a.x)*180/Math.PI}deg)`}}/>})}{nodes.map(n=><div key={n.id} className={"node "+n.kind} style={{left:n.x+"%",top:n.y+"%"}} title={n.label}><span></span><small>{n.label}</small></div>)}<div className="maptitle">VENUE DIGITAL TWIN · LIVE AGENT SIMULATION</div></div><div className="timeline">Simulation time: {snap?.state.sim_time_min.toFixed(1)||"0.0"} min · Status: {snap?.state.status||"standby"} · Exited: {snap?.state.total_exited||0}</div></div>
 <aside className="right"><section><label>RISK ENGINE</label><div className={"risk "+(snap?.state.risk_level||"LOW").toLowerCase()}>{snap?.state.risk_level||"LOW"} <b>{Math.round(snap?.state.risk_score||0)}/100</b></div></section><section><label>BOTTLENECKS</label>{snap?.state.bottlenecks.length?<ul>{snap.state.bottlenecks.map(x=><li key={x}>{x}</li>)}</ul>:<p>All monitored corridors are below threshold.</p>}</section><section><label>INCIDENTS</label>{snap?.state.events.length?<ul>{snap.state.events.slice(-5).map((x:any,i)=><li key={i}>{x.type} · {x.node_id||"system"}</li>)}</ul>:<p>No incidents recorded.</p>}</section><section><label>OPERATOR NOTE</label><p>Agents route through the venue graph. Emergency closures disable affected edges and trigger deterministic rerouting. Risk calculations remain deterministic and auditable.</p></section></aside></main></div>}
export default App;
